sudo: required
services:
- docker
install:
- set -e
jobs:
  include:
  - stage: unit test
    language: go
    go:
    - 1.11.x
    env:
    - GO111MODULE=on
    go_import_path: github.com/buildpack/lifecycle
    script: |
      make test
