sudo: required
language: go
services:
- docker
go:
- 1.11.x
env:
- GO111MODULE=on
go_import_path: github.com/buildpack/lifecycle
install:
- set -e
script:
- test -z "$(bin/format | tee >(cat >&2))"
- go test -v
