name: lifecycle-image

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=VERSION::`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: buildpacksio/lifecycle
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: .github/workflows/lifecycle-image/Dockerfile
          buildargs: LIFECYCLE_URI=https://github.com/buildpacks/lifecycle/releases/download/v${{ steps.get_release_version.outputs.VERSION }}/lifecycle-v${{ steps.get_release_version.outputs.VERSION }}+linux.x86-64.tgz
          tags: "latest,${{ steps.get_release_version.outputs.VERSION }}"