name: lifecycle-image

on:
  release:
    types:
      - published

jobs:
  build-lifecycle-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Publish to Registry
        run: |
          LIFECYCLE_VERSION=`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`
          curl -o -L lifecycle.tgz https://github.com/buildpacks/lifecycle/releases/download/v${LIFECYCLE_VERSION}/lifecycle-v${LIFECYCLE_VERSION}+linux.x86-64.tgz
          echo ${{ secret.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          go run ./tools/image/main.go -lifecyclePath ./lifecycle.tgz -tag buildpacksio/lifecycle:${LIFECYCLE_VERSION} -tag buildpacksio/lifecycle:latest
