name: lifecycle-image

on:
  release:
    types:
      - published

jobs:
  build-lifecycle-image-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Publish to Registry
        run: |
          LIFECYCLE_VERSION=`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`
          curl -o lifecycle.tgz -L https://github.com/natalieparellano/lifecycle/releases/download/v${LIFECYCLE_VERSION}/lifecycle-v${LIFECYCLE_VERSION}+linux.x86-64.tgz
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          go run ./tools/image/main.go -lifecyclePath ./lifecycle.tgz -tag natalieparellano/lifecycle:${LIFECYCLE_VERSION}-linux -tag natalieparellano/lifecycle:latest-linux
  build-lifecycle-image-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Publish to Registry
        run: |
          $LIFECYCLE_VERSION=$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f2)
          curl -o lifecycle.tgz -L https://github.com/natalieparellano/lifecycle/releases/download/v${LIFECYCLE_VERSION}/lifecycle-v${LIFECYCLE_VERSION}+windows.x86-64.tgz
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          go run ./tools/image/main.go -lifecyclePath ./lifecycle.tgz -tag natalieparellano/lifecycle:${LIFECYCLE_VERSION}-windows -tag natalieparellano/lifecycle:latest-windows
  create-lifecycle-image-manifest-list:
    needs: [build-lifecycle-image-linux, build-lifecycle-image-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Manifest Life
        run: |
          LIFECYCLE_VERSION=`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create natalieparellano/lifecycle:0.99.20 natalieparellano/lifecycle:0.99.20-linux natalieparellano/lifecycle:0.99.20-windows
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push natalieparellano/lifecycle:0.99.20
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create natalieparellano/lifecycle:latest natalieparellano/lifecycle:latest-linux natalieparellano/lifecycle:latest-windows
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push natalieparellano/lifecycle:latest
